# Generated by Django 3.2.7 on 2021-09-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positions', models.JSONField()),
                ('velocities', models.JSONField()),
                ('masses', models.JSONField()),
                ('collision_tolerance', models.FloatField()),
                ('escape_tolerance', models.FloatField()),
            ],
        ),
    ]
