# Generated by Django 3.2.7 on 2021-09-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210909_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrator',
            name='velocity_orbits',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
