# Generated by Django 3.2.7 on 2021-09-18 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_integrator_velocity_orbits'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrator',
            name='steps',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
    ]
